# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [8]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.94151713 0.71489483 0.5572283  ... 0.94079308 0.93306745 0.49609388]
 [0.48479702 0.66501268 0.84164744 ... 0.1748827  0.7819451  0.72200837]
 [0.61226692 0.56368294 0.99270117 ... 0.37796695 0.84451851 0.52683768]
 ...
 [0.21318011 0.20573128 0.37708822 ... 0.27293771 0.93391272 0.38077143]
 [0.61682901 0.23425443 0.16083267 ... 0.81673387 0.94192116 0.16569679]
 [0.23728994 0.74557713 0.94159723 ... 0.38003565 0.36959777 0.07999235]]
[[0.2690895  0.31910181 0.86595654 ... 0.94720037 0.31553136 0.46562976]
 [0.33563582 0.66655784 0.86273069 ... 0.97143977 0.5381098  0.97740595]
 [0.54444828 0.03258531 0.83389381 ... 0.27340461 0.36821101 0.81562373]
 ...
 [0.53577047 0.47943135 0.43642295 ... 0.33825048 0.30032976 0.91272433]
 [0.38595203 0.61086124 0.67830052 ... 0.77193003 0.1790406  0.66248225]
 [0.55605297 0.54533918 0.52080818 ... 0.11987674 0.93605978 0.19416069]]


Без использования numpy

In [4]:
def mult(a, b):
    n = len(a)
    result = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [5]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [9]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 700 ms, sys: 0 ns, total: 700 ms
Wall time: 705 ms


In [10]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.7 ms, sys: 4.01 ms, total: 5.71 ms
Wall time: 8.55 ms


In [11]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5301537814593758e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [12]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.82641854 0.17031486 0.94691884] [0.33824944 0.75428853 0.43154475]


In [13]:
def scalar_product(a,b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

In [14]:
def np_scalar_product(a,b):
    result = np.dot(a, b)
    return result

In [15]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 17 µs, sys: 3 µs, total: 20 µs
Wall time: 23.8 µs
CPU times: user 128 µs, sys: 0 ns, total: 128 µs
Wall time: 131 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:**  методы numpy оказываются эффективнее потому что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора)

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [16]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  if len(a) > 0 and len(a[0]) == len(a):
    diagonal = np.diag(a)
    even_diagonal = diagonal[::2]
    return np.sum(even_diagonal)
  return 0

In [17]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 3, 5, 1, 5],
       [1, 4, 3, 1, 5],
       [1, 2, 4, 1, 4],
       [1, 4, 4, 6, 4],
       [6, 5, 7, 8, 1]])

In [18]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 153 µs, sys: 0 ns, total: 153 µs
Wall time: 159 µs


11

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [19]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cumulative_sums = np.cumsum(X, axis=1)
    result = cumulative_sums / np.arange(1, X.shape[1] + 1)
    return result

In [20]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[9.99711782e-01 4.14983819e-01 9.11758015e-01 7.78693436e-02
 1.28777227e-01 8.98824433e-01 1.63911121e-01 5.89352903e-01
 6.23329189e-01 7.84851783e-01 4.23859651e-01 2.94426659e-01
 6.91703313e-01 7.71426692e-01 8.30347135e-01 7.99090094e-01
 2.91885847e-01 4.67127432e-01 8.42833449e-01 6.37809294e-01
 5.78567991e-01 2.23002645e-01 7.45680018e-01 3.30200132e-01
 3.51869276e-01 4.15524503e-01 8.61726682e-01 9.80140948e-01
 4.39932313e-01 9.89945785e-01 9.19846399e-01 2.04904573e-01
 9.69314806e-01 6.96768489e-01 8.08959222e-01 9.07379925e-03
 2.07624912e-01 4.46465395e-01 2.85884347e-01 1.27074204e-01
 9.35748354e-01 3.81981415e-01 6.35587961e-01 4.37453753e-01
 3.78782636e-01 7.70857602e-01 1.77015506e-01 4.59617051e-01
 8.06823656e-01 4.37565118e-01 3.80052220e-01 1.47822326e-02
 5.14624709e-01 8.71376127e-01 4.36644270e-01 7.40926866e-02
 6.64184625e-01 9.14959467e-02 5.19516666e-01 7.22847979e-01
 2.89885208e-01 4.41460595e-01 4.03779491e-01 5.44737873e-01
 8.10336950e-01 5.083391

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [21]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    if len(a) == 0:
        return np.array([]), np.array([])
    current_element = a[0]
    count = 1
    encoded_elements = []
    element_count = []
    for element in a[1:]:
        if element == current_element:
            count += 1
        else:
            encoded_elements.append(current_element)
            element_count.append(count)

            current_element = element
            count = 1
    encoded_elements.append(current_element)
    element_count.append(count)

    return np.array(encoded_elements), np.array(element_count)

In [27]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(np_encode(X))

CPU times: user 28 µs, sys: 5 µs, total: 33 µs
Wall time: 35.8 µs
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [25]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    transformed_X = X.copy()
    transformed_X[1::2] = a
    transformed_X[::2] = transformed_X[::2] ** 3
    reversed_transformed_X = transformed_X[::-1]
    result = np.concatenate((X, reversed_transformed_X))

    return result

In [26]:
X = np.array([i for i in range(1, 10, 2)])
print(X)
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(np_transformation(X, 5))

[1 3 5 7 9]
CPU times: user 62 µs, sys: 11 µs, total: 73 µs
Wall time: 78 µs
[  1   3   5   7   9 729   5 125   5   1]
